name: Run Tests

on:
  push:
      branches: [ "main" ]
jobs:
  test:
    name: Packer Build
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: test_dba

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Install dependencies
        run: npm install
   
      - name: Create database
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -u${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} -e 'DROP DATABASE IF EXISTS test_dba;'
          sudo mysql -u${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} -e 'CREATE DATABASE test_dba;'
          

      - name: Run Tests    
        run: npm test
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: test_dba
          DB_USER: ${{ secrets.MYSQL_USER }}
          DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          PORT: 8080

      - name: Authenticate with Service Account Key
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
         credentials_json: '${{ secrets.GCP_CREDENTIAL }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
          unzip packer_1.7.5_linux_amd64.zip
          sudo mv packer /usr/local/bin/packer
          packer version     

      - name : Zipping all files
        run: zip -r webapp.zip .

      - name : Packer Installation
        run :  packer init .

      - name: Check Packer file formatting
        run: packer fmt gcp.pkr.hcl
        
      - name: Check Packer file validation
        run: packer validate -var 'project_id=${{ secrets.GCP_PROJECT }}' -var 'zone=${{ secrets.GCP_ZONE }}' -var 'script_path=${{ secrets.SCRIPT_PATH }}' -var 'app_file_src=${{ secrets.APP_FILE_SRC }}' -var 'app_file_dest=${{ secrets.APP_DEST_SRC }}' -var 'source_image_family=${{ secrets.SRC_IMG_FAM }}' -var 'ssh_username=${{ secrets.SSH_USER }}' -var 'image_family=${{ secrets.IMG_FAM }}' gcp.pkr.hcl
      
      - name: Buid Images
        run: packer build -var 'project_id=${{ secrets.GCP_PROJECT }}' -var 'zone=${{ secrets.GCP_ZONE }}' -var 'script_path=${{ secrets.SCRIPT_PATH }}' -var 'app_file_src=${{ secrets.APP_FILE_SRC }}' -var 'app_file_dest=${{ secrets.APP_DEST_SRC }}' -var 'source_image_family=${{ secrets.SRC_IMG_FAM }}' -var 'ssh_username=${{ secrets.SSH_USER }}' -var 'image_family=${{ secrets.IMG_FAM }}' gcp.pkr.hcl
      
      - name: Create new Instance Template version
        run: |
          gcloud compute instance-templates create ${{ secrets.VM_TEMP_NAME }} \
            --project=${{ secrets.GCP_PROJECT }} \
            --machine-type=${{ secrets.VM_MACHINE_TYPE }} \
            --network-interface=subnet=${{ secrets.VM_SUBNET }} \
            --instance-template-region=${{ secrets.REGION }} \
            --region=${{ secrets.REGION }} \
            --metadata=startup-script='#!/bin/bash
              sudo cat << EOF | sudo tee /opt/csye6225/.env
              DB_HOST="${{ secrets.CLOUDSQL_DBHOST }}"
              DB_USER="${{ secrets.CLOUDSQL_DBUSER }}"
              DB_PASSWORD="${{ secrets.CLOUDSQL_DBPASSWORD }}"
              DB_NAME="${{ secrets.CLOUDSQL_DBNAME }}"
              PORT="${{ secrets.PORT }}"
              DB_PORT="${{ secrets.CLOUDSQL_DBPORT }}"
              PROJECT_ID= "${{ secrets.GCP_PROJECT }}"
              TOPIC_NAME="${{ secrets.TOPIC_NAME }}"
          EOF

                  sudo systemctl restart csye6225.service
                  sudo systemctl restart google-cloud-ops-agent
                ' \
                --service-account=${{ secrets.VM_SERVICE_ACCOUNT }} \
                --scopes=${{ secrets.VM_SA_SCOPES }}\
                --tags=${{ secrets.VM_TAGS }} \
                --create-disk=auto-delete=yes,boot=yes,device-name=persistent-disk-0,image-family=${{ secrets.IMAGE_FAMILY }},kms-key=${{ secrets.VM_KMS_KEY }},size=${{ secrets.VM_DISK_SIZE }},type=${{ secrets.VM_DISK_TYPE }}


                    

      - name: Configure managed instance group
        run: |
          gcloud compute instance-groups managed set-instance-template ${{ secrets.INSTANCE_GROUP_NAME }} \
          --template=${{ secrets.INSTANCE_TEMP_PATH}} \
          --region=${{ secrets.REGION }}

      - name: Start rolling update
        run: |
          gcloud compute instance-groups managed rolling-action start-update ${{ secrets.INSTANCE_GROUP_NAME }} \
          --version=template=${{ secrets.INSTANCE_TEMP_PATH}} \
          --region=${{ secrets.REGION }} \
          --max-surge 1 \
          --max-unavailable 0

      - name: Monitor update progress
        run: |
          gcloud compute instance-groups managed wait-until ${{ secrets.INSTANCE_GROUP_NAME }} \
          --version-target-reached \
          --region=${{ secrets.REGION }}