name: Run Tests

on:
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
jobs:
  test:
    name: Test with MySQL
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: some_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Install dependencies
        run: npm install
   
      - name: Create database
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -u${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} -e 'DROP DATABASE IF EXISTS some_db;'
          sudo mysql -u${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} -e 'CREATE DATABASE some_db;'
          

      - name: Run Tests    
        run: npm test
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: some_db
          DB_USER: ${{ secrets.MYSQL_USER }}
          DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          PORT: 8080
        
