name: Run Tests

on:
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
jobs:
  test:
    name: Test with MySQL
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: ${{secret.MYSQL_DATABASE }}
          MYSQL_PASSWORD: ${{secret.MYSQL_PASSWORD}}
          MYSQL_USER: ${{secret.MYSQL_USER}}
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Install dependencies
        run: npm install
   
      - name: Create database
        run: |
          sudo systemctl start mysql
          mysql -h 127.0.0.1 -u  ${{secret.MYSQL_USER}} -p${{secret.MYSQL_PASSWORD}} -e "CREATE DATABASE IF NOT EXISTS ${{secret.MYSQL_DATABASE}};"

      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: ${{secret.MYSQL_USER}}
          DB_PASSWORD: ${{secret.MYSQL_PASSWORD}}
          DB_NAME: ${{secret.MYSQL_DATABASE}}
          PORT: 8080
        run: npm test
