name: Packer Format Check

on:
   push:
    branches: [ "main" ]
   pull_request:
    branches: [ "main" ]

jobs:
 
  build:
    name: Packer Validate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Packer
      run: |
        wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
        unzip packer_1.7.5_linux_amd64.zip
        sudo mv packer /usr/local/bin/packer
        packer version

    - name : Zipping all files
      run: zip -r webapp.zip .

    - name : Packer Installation
      run :  packer init .

    - name: Check Packer file formatting
      run: packer fmt -check gcp.pkr.hcl
      
    - name: Check Packer file formatting
      run: packer validate -var 'project_id=dev-project-414723' -var 'zone=us-east4-b' -var 'script_path=setup.sh' -var 'app_file_src=webapp.zip' -var 'app_file_dest=/home/admin/webapp.zip' gcp.pkr.hcl 